// <auto-generated />
namespace EmployeeConsumerApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateauthencation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateauthencation));
        
        string IMigrationMetadata.Id
        {
            get { return "202011180213521_update-authencation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
